# Generated by Django 2.1.4 on 2020-03-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezcall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.AddField(
            model_name='phone',
            name='mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='userip',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
